---
title: "Chapter 4 pt 2 (Module 5) Notes"
output:
  md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* **Section 1** -- Required Competencies
	* Analytics role to go from data collection to delivering information or knowledge to the business
	* The business can experience considerable loss if analytics staff are not competent at their position
	* A lack of good analytics staff can also cause a loss in the investment made in the technical environment
	* Aims of this section
		* Mapping process
		* Start with specific information requirements
		* Identify specific analytical techniques
		* Present a model that can be used in the dialogue between management and analyst
	* A caution: requesting a specific analysis be done can result in misalignment with analytics staff.
		* As the text suggests, always start with the business needs and allow analytics staff to work out the necessary methods
	* See slides for the balance of the summary
* **Section 2** -- Quantitative Method Summary
	* See slides for notes (there's no need for me to re-format these notes)
* **Section 3** -- 
	* Business requirements describe the characteristics of a proposed system from the viewpoint of the system's end user. (Wikipedia)
	* The analyst must be able to understand and translate the business user's thoughts and needs into something that can be answered through analyst or data manager or report developer competencies.
	* Definition of the problem
		* Need to place the specific task in a broader context
		* Relate to other tasks
		* Need to know how value will be added to a specific business process
		* OR the person making the request must relate task to a strategic initiative
		* “The analyst must be extremely careful in taking on the task”
	* Definition of delivery
		* Specify in which media the analysis must be delivered (report, dashboard, operational data)
		* How and when the delivery will take place
		* Need to have clear agreement on roles and responsibilities after the delivery
		* Who is notified of errors or breakdowns
		* Everyone needs to understand that errors will happen and to plan for them
	* Definition of content
		* Content = information provided
		* Often the deliverable will be new for the various users
		* Plan to train new users on functionality and interpretation of results
		* Help users understand where the content may be unclear or imprecise 



