---
title: "Chapter 3 Notes"
output:
  md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* **Section 1** -- Introduction
    * Identify how to get from having some overall objectives for a department to specifying information and data requirements.
    * We discuss the relationship between BA and the operational level and the relationship between strategic plans and how to operationalize them with a focus on the BA function's deliveries.
    *  Just as we need to formulate a customer relationship management (CRM) strategy to reflect the overall strategy and its requirements to the CRM function, we also need to have an information strategy in place that reflects the information and data requirements placed by corporate strategy to the BA function.
    * Corporate Strategy: Set of objectives to meet a particular business goal
    * Information Strategy: set of data requirements to achieve the corporate strategy
    * Lead
        * Definition -- “Something that comes before”
        * Collection strategy -- Knowledge necessary for getting a process started/improve existing
        * Systems -- Typically comes from ad hoc projects
    * Lag
        * Defintion -- “Something that comes after”
        * Collection Strategy -- Continuous measuring of how the process is meeting objectives
        * Systems -- Conventionally automated reporting on key indicators
* **Section 2** -- Summerhouse Example
    * Introduce some concepts
        * KPIs
        * Performance managment 
        * Information requirements
        * Dashboards
    * Analytics must answer the following questions
        * Status – have we gone far enough in relation to how long we’ve been on the road
        * Trend – are we accelerating up or down, or is our speed constant?
        * Projection – given our speed and how far we’ve gone, will we reach the summerhouse at the expected time?
    * KPIs
        * KPIs describe the relationship between the organization and its main objectives
        * Describe when the company is doing well and when it is off track
        * The existence of KPIs along with their associated targets allows the business to adjust tactics (keeping strategy fixed)
        * Provide the organization with a memory so learning can be derived from projects
    * What can we learn when KPIs are not meeting their targets
        * Lack of strategic focus
            * KPI is not visible to relevant staff
            * Visible but no one cares
            * Strategy has shifted
            * Mistrust in the data
        * Lack of competency
            * Business executing correctly but KPI is not reaching the desired level
            * Need to research competencies necessary to perform task well and competencies present in the business
        * Changing environment
            * Are we operating under different conditions than when strategy developed?
            * Were the targets set inappropriately?
* **Section 3** -- Establishing a business process
    * Follow steps for establishing a new business process
        * Level 1 -- identify objectives
        * Level 2 -- Identify an operational strategy
        * Level 3 -- Identify the critical success factors
        * Level 4 -- Idnetify lead and lag information
    * Critical success factors
        * Elements of the plan that must have a successful outcome if the plan as a whole is to succeed
        * If just one of the success factors fails, the whole strategy is expected to fail, meaning our objectives will not be met
    * Different types of information
        * Strategic Information
            * Definition: Information that would be used to create a digital marketing strategy.
            * Example: Should sales turnover be supported through new customer acquisition, selling more to existing customers or focusing on customer retention?
            * More generally: What should we do?
        * Tactical Information
            * Definition : Creation and optimization of new/existing campaigns.
            * Example: Who should receive this campaign? When should we introduce it? Should the campaign be time limited?
            * More generally: How should we do it?
        * Operational Information
            * Definition : Concrete information that will drive action against campaigns.
            * Example: Which customers should we contact and which offers should be made?
            * More generally: Now we do it.
* **Section 4** -- Optimize a busines process
    * Optimization is the process of adjusting your actions to meet some goal subject to a set of constraints
    * Two ways to optimize
        * Ensure a better use of resources
        * Improve the results of the process
    * Strategy will serve as a set of constraints (restrict scope)
        * Ex. Cut costs while maintaining customer satisfaction
    * Revisit lead/lag data
        * At this point, need to add additional tags to data so we know which tactics were done
        * Need to save information on what was done and when
        * Later will want to understand which tactics produced results
        * Want to do more of what worked and less of what didn’t










